### ISSUE TITLE
Initialization when v-grid element is hidden/not in DOM

### ISSUE THREAD

**Issue by don-bluelinegrid** [aurelia-ui-toolkits/aurelia-v-grid#56] opened 2016-09-16 21:10 UTC
Hi Vegar,

In my application, I have essentially a master-detail view, where I have on the left a list of items, and on the right the detail of the item.  In this case, the item is a community, and a community has a list of members, so the right-side detail shows the list of members in the community.  This right-side detail is where I would use the v-grid.

The way I currently have this working (without using v-grid) is that I have two components:
community.ts/community.html
community-detail.ts/community-detail.html

I am using the Aurelia `<compose>` to include the detail view into the main view; inside that, I am using `if.bind='selectedCommunity!=null'` so that the detail view is not shown until an item is selected.

With this, when I try to include the v-grid into the community-detail.html, I am getting an error like this:
`
Unhandled rejection Error: Error invoking ViewSlot. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: Cannot set property 'viewSlot' of undefined
Inner Error Stack:
TypeError: Cannot set property 'viewSlot' of undefined
    at new ViewSlot (http://localhost:9000/aurelia.bundle.js:2798:21)
    at Object.invoke (http://localhost:9000/aurelia.bundle.js:577:12)
    at InvocationHandler.invoke (http://localhost:9000/aurelia.bundle.js:554:166)
    at Container.invoke (http://localhost:9000/aurelia.bundle.js:816:23)
    at StrategyResolver.get (http://localhost:9000/aurelia.bundle.js:295:35)
    at Container.get (http://localhost:9000/aurelia.bundle.js:747:39)
    at Object.invokeWithDynamicDependencies (http://localhost:9000/aurelia.bundle.js:565:25)
    at InvocationHandler.invoke (http://localhost:9000/aurelia.bundle.js:554:166)
    at Container.invoke (http://localhost:9000/aurelia.bundle.js:816:23)
    at StrategyResolver.get (http://localhost:9000/aurelia.bundle.js:295:35)
    at Container._get (http://localhost:9000/aurelia.bundle.js:761:39)
    at Container._get (http://localhost:9000/aurelia.bundle.js:764:26)
    at Container._get (http://localhost:9000/aurelia.bundle.js:764:26)
    at Container._get (http://localhost:9000/aurelia.bundle.js:764:26)
    at Container._get (http://localhost:9000/aurelia.bundle.js:764:26)
    at Container.get (http://localhost:9000/aurelia.bundle.js:750:26)
`

I'm guessing that this is related to having the v-grid inside the `<compose>` and having it excluded from the DOM with the `if.bind`.  This seems like a fairly common case though.  I did try to put the loadData() and callRemoteServer() calls into the view-model `attached()` function, but that doesn't really help, because it looks like when using `<compose>` the `attached()` is called when the containing view is attached.

Do you have any advice on how to handle this?  right now, I cannot get a grid to display in my view at all.

Thanks,
Don

**Comment by vegarringdal** [comment] 2016-09-16 21:32
Not able to test anything atm where Im at, will hopefully get a better chance to answer tomorrow a few hours after I wake up 😂 , but in my gist I use own component for the detail views maybe thats a better way, that share the main list components/app.js current entity.
That way I separate the app into components, thats what you want to do with you application.

So much I would like to know better, compose part I havent really touched that much.

When I think about it, what about just creating a own class for the list, that class you use with the grid, and any component that want to use the data, that way you could keep the status of the current data when switching views etc, since it will be cached. (might be overthinking it here btw)

What database are you using btw, if I can ask, I have a idea of a app I want to create that was the main bases for the creation of the grid, and one of the reason I want the virtual scrolling to work.
Postgres ?

**Comment by don-bluelinegrid** [comment] 2016-09-16 21:54
Database is mySQL, accessed through a Java Spring RESTful API.

**Comment by don-bluelinegrid** [comment] 2016-09-16 21:56
>in my gist I use own component for the detail views maybe thats a better way, that share the main list components/app.js current entity.

I do the same - in my setup, I have a `selectedCommunity` which is the current entity.  This is inherited by the `compose` view-model, so it is shared.

**Comment by vegarringdal** [comment] 2016-09-17 16:06
Hi, what version of the grid are you using, I didnt build release of the one with virtual scrolling, so this could be the problem, see here to you can use it  [without installing](https://aurelia-ui-toolkits.gitbooks.io/aurelia-v-grid-docs/content/chap07/#without-installing)

If thats not the problem then:
Are you able to reproduce the bug in one of the gist.run by modifying one, something like this one?
https://gist.run/?id=fbd4e9f36d5eacd120dfac8184601f8d

**Comment by don-bluelinegrid** [comment] 2016-09-17 16:12
"version": "0.2.5"

**Comment by don-bluelinegrid** [comment] 2016-09-17 16:14
I'm fairly certain that the problem I'm seeing, with 
`
Inner Error:
Message: Cannot set property 'viewSlot' of undefined
Inner Error Stack:
TypeError: Cannot set property 'viewSlot' of undefined
at new ViewSlot (http://localhost:9000/aurelia.bundle.js:2798:21)
`
is due to a conflict between the custom component JS code looking for the DOM element associated with the v-grid, when the DOM element doesn't exist because it has been omitted from the DOM using `if.bind`.

**Comment by vegarringdal** [comment] 2016-09-17 16:46
Ahh, you remove the grid, didnt read that very good today
Maybe show.bind is better, html is just hidden not removed, it it will actually load faster..

**Comment by vegarringdal** [comment] 2016-09-17 16:56
Is this what you are trying to do:

https://gist.run/?id=4109a7c3502b4a7dfa3b292c2326164c

Show works, using if.bind creates a mess atm in the gist, since grid is recreated, but somehow cached also

**Comment by don-bluelinegrid** [comment] 2016-09-17 17:41
OK, so it sounds like you were able to reproduce the errors I saw when using if.bind.
I will try switching to show.bind to see if that makes a difference.  Right now my code is in a bad state, from trying out other grid components.

**Comment by vegarringdal** [comment] 2016-09-17 17:45
>OK, so it sounds like you were able to reproduce the errors I saw when using if.bind.

I will have a and see if I can improve that part...


>I will try switching to show.bind to see if that makes a difference. Right now my code is in a bad state, from trying out other grid components.

Testing can create a code mess :-)

**Comment by don-bluelinegrid** [comment] 2016-09-17 17:52
Using show.bind does not change anything in my code.  I still see:

`
Unhandled rejection Error: Error invoking ViewSlot. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: Cannot set property 'viewSlot' of undefined
Inner Error Stack:
TypeError: Cannot set property 'viewSlot' of undefined
    at new ViewSlot (http://localhost:9000/aurelia.bundle.js:2923:21)
`

Your Gist does not match my example, because you have all of the HTML template in one file - for the grid, and the detail.  My example is like this:

left-side list => item selection exposes right-side
right-side grid => display nested list of selected item, using v-grid

There is something about the v-grid implementation that must have a dependency on the grid DOM being created *before* the model, and this causes a problem with using <compose> or <require> in a template.

**Comment by don-bluelinegrid** [comment] 2016-09-17 18:02
I have now removed the < compose >, and have moved the v-grid declaration into the main page.  I still see the same error, even without using compose and with the grid in the main view, and using show.bind.  I have an extremely simplified version of the grid, with one column, and still see this error.

**Comment by don-bluelinegrid** [comment] 2016-09-17 18:03
I have also removed show.bind to just always show the grid, and also see the same error.

**Comment by vegarringdal** [comment] 2016-09-17 18:29
are you able to make a sample in the gist.run with how you use compose so I see it better whats going on

**Comment by don-bluelinegrid** [comment] 2016-09-17 18:38
Try this:

https://gist.run/?id=243c3844c9270fee9ed8477945061fd4

the difference is that your (and this) example use pre-loaded local data, instead of remote data returned in a Promise.  The Gist above shows the code structure using < compose >, but there is no error.  I suspect that this is due to not using remote data/Promise.  Perhaps there's some assumption in the grid code that requires a data array to be present when the grid is displayed/rendered.

**Comment by don-bluelinegrid** [comment] 2016-09-17 18:39
YOu can try changing this so that remote data is loaded in the composed.js file.

**Comment by vegarringdal** [comment] 2016-09-17 18:59
Ill have a look

**Comment by vegarringdal** [comment] 2016-09-17 19:19
tried adding remote data, no error

https://gist.run/?id=1c0eb8ffe49b565f9cd7c24bd78feeb9

**Comment by vegarringdal** [comment] 2016-09-18 12:53
Atm the biggest issue would be multi selection
To be as fast as possible Ive used ID/attribute with a set to keep track, when using remote scrolling that would need to be replaced by keeping track of rows, it did do that at first but was not a good solution when over 100k-900k rows when sorting, due to a the work I would need to do to keep the correct rows highlighted, for multi selection to really work there would haveto be a server side code to correct it when sorting/filtering

Would need to keep track of selected ranges, selected rows and not selected (3 arrays) that server also sent back on.

Or just let user select many just not ranges outside what it got in its cache

**Comment by don-bluelinegrid** [comment] 2016-09-18 15:13
I'm not clear why the selection is different for this virtual/remote scrolling compared to a normal paging scenario.

In normal paging there is a total remote set (say 1000), and at any moment a subset of the total (say 25) is visible.  For multi-selection across pages, it's necessary to track a collection of selected indexes separate from the visible data subset.  This is the same case for remote scrolling - we'd need to track the selection in a collection.

The actual physical ID of the data item would be the preferred value to track, and that could be done by using a v-grid attribute like 'v-grid-id-property', to specify the ID property name, incase it's a property name like 'memberId'.

Don

**Comment by vegarringdal** [comment] 2016-09-18 16:36
Yes

But when you do virtual scrolling, say you have loaded the first 40 (total count 2000)
select 1 row, then use scrollbar to the middle, hold shift down and select 1, then the id would be useless, since we will be on around row 1000, and only have the 40 first and 40 around what ever is in the middle.

Its only the ranges that will cause real issues

**Comment by vegarringdal** [comment] 2016-09-25 19:36
Got a little project where Im making a rest api datasource for wakanda database (wakanda.org), after Ive made that I will heavily modify a version of the grid for using that datesource, maybe that version will be better for this loading while scrolling. I need that to work on the modified version, Ill try and not mess it up to much so others can hook into it.

Ill post here when Ive gotten started, Ill know better in a week or two how this will go 😂

**Comment by vegarringdal** [comment] 2016-10-06 11:50
Never got any response back on this so closing it, guessing you figured out the display issues?
This was the latest gist where I used the compose, and didn not get any errors
https://gist.run/?id=1c0eb8ffe49b565f9cd7c24bd78feeb9

**Closed by vegarringdal** 2016-10-06 11:50 UTC
